version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  
  map-frontend: # name of the first service
    build: map-frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding

  map-backend: #name of the second service
    build: map-backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001" #specify ports forewarding
    links:
      - database # link this service to the database service
